### ISSUE TITLE
Add SameSite support for the session cookie

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-session-cache#1]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-session-cache/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-session-cache/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Add SameSite support for the session cookie

---

Originally posted by @sandfoxme at https://github.com/zendframework/zend-expressive-session-cache/issues/10

**Comment by geerteltink** [comment]
Closed by #3
